apiVersion: batch/v1
kind: CronJob
metadata:
  name: your-cron-job
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: woomark
            image: colepalm/wookmark:0.6.0
          imagePullSecrets:
          - name: regcred
          restartPolicy: OnFailure
