apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: your-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: woomark
            image: colepalm/wookmark:0.6.0
          restartPolicy: OnFailure
